"""
This type stub file was generated by pyright.
"""

from evdev.device import AbsInfo, DeviceInfo, EvdevError, InputDevice
from evdev.events import AbsEvent, InputEvent, KeyEvent, RelEvent, SynEvent, event_factory
from evdev.uinput import UInput, UInputError
from evdev.util import categorize, list_devices, resolve_ecodes, resolve_ecodes_dict
from evdev import ecodes, ff

