"""
This type stub file was generated by pyright.
"""

from evdev import eventio

class EventIO(eventio.EventIO):
    def async_read_one(self): # -> Future[Any]:
        '''
        Asyncio coroutine to read and return a single input event as
        an instance of :class:`InputEvent <evdev.events.InputEvent>`.
        '''
        ...
    
    def async_read(self): # -> Future[Any]:
        '''
        Asyncio coroutine to read multiple input events from device. Return
        a generator object that yields :class:`InputEvent <evdev.events.InputEvent>`
        instances.
        '''
        ...
    
    def async_read_loop(self): # -> ReadIterator:
        '''
        Return an iterator that yields input events. This iterator is
        compatible with the ``async for`` syntax.

        '''
        ...
    
    def close(self): # -> None:
        ...
    


class ReadIterator:
    def __init__(self, device) -> None:
        ...
    
    def __iter__(self): # -> Self:
        ...
    
    def __next__(self):
        ...
    
    def __aiter__(self): # -> Self:
        ...
    
    def __anext__(self): # -> Future[Any]:
        ...
    


