"""
This type stub file was generated by pyright.
"""

'''
This module provides the :class:`InputEvent` class, which closely
resembles the ``input_event`` struct defined in ``linux/input.h``:

.. code-block:: c

    struct input_event {
        struct timeval time;
        __u16 type;
        __u16 code;
        __s32 value;
    };

This module also defines several :class:`InputEvent` sub-classes that
know more about the different types of events (key, abs, rel etc). The
:data:`event_factory` dictionary maps event types to these classes.

Assuming you use the :func:`evdev.util.categorize()` function to
categorize events according to their type, adding or replacing a class
for a specific event type becomes a matter of modifying
:data:`event_factory`.

All classes in this module have reasonable ``str()`` and ``repr()``
methods::

    >>> print(event)
    event at 1337197425.477827, code 04, type 04, val 458792
    >>> print(repr(event))
    InputEvent(1337197425L, 477827L, 4, 4, 458792L)

    >>> print(key_event)
    key event at 1337197425.477835, 28 (KEY_ENTER), up
    >>> print(repr(key_event))
    KeyEvent(InputEvent(1337197425L, 477835L, 1, 28, 0L))
'''
class InputEvent:
    '''A generic input event.'''
    __slots__ = ...
    def __init__(self, sec, usec, type, code, value) -> None:
        ...
    
    def timestamp(self):
        '''Return event timestamp as a float.'''
        ...
    
    def __str__(s) -> str:
        ...
    
    def __repr__(s): # -> str:
        ...
    


class KeyEvent:
    '''An event generated by a keyboard, button or other key-like devices.'''
    key_up = ...
    key_down = ...
    key_hold = ...
    __slots__ = ...
    def __init__(self, event, allow_unknown=...) -> None:
        '''
        The ``allow_unknown`` argument determines what to do in the event of an event code
        for which a key code cannot be found. If ``False`` a ``KeyError`` will be raised.
        If ``True`` the keycode will be set to the hex value of the event code.
        '''
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(s): # -> str:
        ...
    


class RelEvent:
    '''A relative axis event (e.g moving the mouse 5 units to the left).'''
    __slots__ = ...
    def __init__(self, event) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(s): # -> str:
        ...
    


class AbsEvent:
    '''An absolute axis event (e.g the coordinates of a tap on a touchscreen).'''
    __slots__ = ...
    def __init__(self, event) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(s): # -> str:
        ...
    


class SynEvent:
    '''
    A synchronization event. Used as markers to separate events. Events may be
    separated in time or in space, such as with the multitouch protocol.
    '''
    __slots__ = ...
    def __init__(self, event) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(s): # -> str:
        ...
    


event_factory = ...
__all__ = ('InputEvent', 'KeyEvent', 'RelEvent', 'SynEvent', 'AbsEvent', 'event_factory')
