"""
This type stub file was generated by pyright.
"""

'''
Usage: evtest [options] [<device>, ...]

Input device enumerator and event monitor.

Running evtest without any arguments will let you select
from a list of all readable input devices.

Options:
  -h, --help          Show this help message and exit.
  -c, --capabilities  List device capabilities and exit.
  -g, --grab          Other applications will not receive events from
                      the selected devices while evtest is running.

Examples:
  evtest /dev/input/event0 /dev/input/event1
'''
input = ...
def parseopt(): # -> tuple[Values, list[str]]:
    ...

def main(): # -> Literal[0]:
    ...

def select_devices(device_dir=...): # -> list[InputDevice]:
    '''
    Select one or more devices from a list of accessible input devices.
    '''
    ...

def print_capabilities(device): # -> None:
    ...

def print_event(e): # -> None:
    ...

def toggle_tty_echo(fh, enable=...): # -> None:
    ...

if __name__ == '__main__':
    ret = ...
