"""
This type stub file was generated by pyright.
"""

from evdev.eventio_async import EventIO

class UInputError(Exception):
    ...


class UInput(EventIO):
    '''
    A userland input device and that can inject input events into the
    linux input subsystem.
    '''
    __slots__ = ...
    @classmethod
    def from_device(cls, *devices, filtered_types=..., **kwargs): # -> Self:
        '''
        Create an UInput device with the capabilities of one or more input
        devices.

        Arguments
        ---------
        devices : InputDevice|str
          Varargs of InputDevice instances or paths to input devices.

        filtered_types : Tuple[event type codes]
          Event types to exclude from the capabilities of the uinput device.

        **kwargs
          Keyword arguments to UInput constructor (i.e. name, vendor etc.).
        '''
        ...
    
    def __init__(self, events=..., name=..., vendor=..., product=..., version=..., bustype=..., devnode=..., phys=..., input_props=...) -> None:
        '''
        Arguments
        ---------
        events : dict
          Dictionary of event types mapping to lists of event codes. The
          event types and codes that the uinput device will be able to
          inject - defaults to all key codes.

        name
          The name of the input device.

        vendor
          Vendor identifier.

        product
          Product identifier.

        version
          Version identifier.

        bustype
          Bustype identifier.

        phys
          Physical path.

        input_props
          Input properties and quirks.

        Note
        ----
        If you do not specify any events, the uinput device will be able
        to inject only ``KEY_*`` and ``BTN_*`` event codes.
        '''
        ...
    
    def __enter__(self): # -> Self:
        ...
    
    def __exit__(self, type, value, tb): # -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __str__(self) -> str:
        ...
    
    def close(self): # -> None:
        ...
    
    def syn(self): # -> None:
        '''
        Inject a ``SYN_REPORT`` event into the input subsystem. Events
        queued by :func:`write()` will be fired. If possible, events
        will be merged into an 'atomic' event.
        '''
        ...
    
    def capabilities(self, verbose=..., absinfo=...):
        '''See :func:`capabilities <evdev.device.InputDevice.capabilities>`.'''
        ...
    
    def begin_upload(self, effect_id): # -> UInputUpload:
        ...
    
    def end_upload(self, upload): # -> None:
        ...
    
    def begin_erase(self, effect_id): # -> UInputErase:
        ...
    
    def end_erase(self, erase): # -> None:
        ...
    


